/* Generated by Together */

package com.xt.comm.privilege;

import java.util.Collection;

/**
 * <p>Title: </p>
 * <p>Description:缺省的权限转换器 </p>
 * <p>Copyright: Copyright (c) 2003年5月</p>
 * <p>Company: </p>
 * @author 郑伟
 * @version 1.0
 */

public class Group
{

    /**
     * 唯一标识部门的字符串。
     */
    private String id;

    /**
     * @link aggregation
     * @directed
     * @clientCardinality 1
     * @label 拥有多个用户
     */
    /*# User users; */
    /**
     * 角色拥有的所有的权限的集合.
     */
    private Collection users;

    /**
     * 用户组里面是否有此用户
     * @param user 用户
     * @return 如果需要检查的用户为空，或者用户组不包含任何用户返回假。如果一个用户被包含到此用户组
     *         <br>时返回真，否则返回假。
     */
    public boolean has (User user)
    {
        if (user == null || this.users == null)
        {
            return false;
        }
        return users.contains(user);
    }

    /**
     * 增加用户
     * @param user 用户
     */
    public void addUser (User user)
    {
        users.add(user);
    }

    /**
     * 删除用户
     * @param user 用户
     */
    public void removeUser (User user)
    {
        users.remove(user);
    }

    public String getId ()
    {
        return id;
    }

    public void setId (String id)
    {
        this.id = id;
    }
}
