/* Generated by Together */

package com.xt.comm.privilege;

import java.util.Collection;
import java.util.Iterator;

/**
 * <p>Title: GreeTea 框架。</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author 郑伟
 * @version 1.0
 */

public class Role
{

    /**
     * @link aggregation
     * @directed
     * @clientCardinality 1
     * @label 拥有
     */
    /*# PrivatePrivilege privileges; */
    /**
     * 角色拥有的所有的权限的集合.
     */
    private Collection privileges;

    /**
     * 角色唯一的Id.
     */
    private String id;

    /**
     * 本角色是否允许此权限访问
     * @param privilege 权限
     * @return 允许访问权限返回真，否则返回假。
     */
    public boolean hasPrivilege (Privilege privilege) {
        if (privilege == null || privileges == null) {
            return false;
        }
        for (Iterator iter = privileges.iterator(); iter.hasNext(); ) {
            Privilege item = (Privilege)iter.next();
            if (item.equals(privilege)) {
                return true;
            }
        }
        return false;
    }

    /**
     * 增加权限
     * @param p 权限
     */
    public void addPrivilege (Privilege p) {
        this.privileges.add(p);
    }

    /**
     * 删除权限
     * @param p 权限
     */
    public void removePrivilege (Privilege p)
    {
        this.privileges.remove(p);
    }

    public String getId ()
    {
        return id;
    }

    public Collection getPrivileges ()
    {
        return privileges;
    }

    public void setId (String id)
    {
        this.id = id;
    }

    public void setPrivileges (Collection privileges)
    {
        this.privileges = privileges;
    }
}
