/* Generated by Together */

package com.xt.comm.privilege;

import java.util.Collection;

/**
 * <p>Title: GreeTea 框架。</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author 郑伟
 * @version 1.0
 */

public interface User
{

    /**
     * 将用户存放在session中的属性名称
     */
    public final static String USER_IN_SESSION = "USER_IN_SESSION";

    /**
     * 得到用户所属的用户组
     * @return 用户所属的用户组
     */
    public Group getGroup ();

    /**
     * 用户是否拒绝此权限；拒绝返回真，否则返回假。
     * @param p 传给用户判断的权限
     * @return 拒绝此权限返回真，否则返回假。
     */
    public boolean decline (Privilege p);

    /**
     * 用户是否拥有此权限。拥有返回真，否则返回假。
     * @param p 传给用户判断的权限
     * @return 拥有此权限返回真，否则返回假。
     */
    public boolean hasPrivilege (Privilege p);

//    /**
//     * 用户对权限进行认证。
//     * @param p 权限。
//     * @return 如果用户拥护该权限，返回真，否则返回假
//     */
//    public boolean authorize (Privilege p);

    public Collection getRoles ();
}
